version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=http://localhost:4000,http://localhost:4002,http://localhost:4003
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  members-dashboard:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  coaches-dashboard:
    build:
      context: .
      dockerfile: coaches-dashboard/Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/
    volumes:
      - ./coaches-dashboard:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  admin-dashboard:
    build:
      context: .
      dockerfile: admin-dashboard/Dockerfile
    ports:
      - "4003:4003"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/
    volumes:
      - ./admin-dashboard:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 